name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test-lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

      - name: Ruff (lint)
        run: |
          if command -v ruff >/dev/null 2>&1; then ruff check .; else echo "ruff not installed"; fi

      - name: MyPy (type-check)
        run: |
          if command -v mypy >/dev/null 2>&1; then mypy app || true; else echo "mypy not installed"; fi

      - name: Pytest
        run: |
          if [ -d tests ]; then pytest -q; else echo "no tests"; fi

  docker-build:
    runs-on: ubuntu-24.04
    needs: test-lint
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image (no push)
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          tags: parrokit-recommender:ci
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Sanity run container
        run: |
          docker run -d -p 8000:8000 --name parrokit-ci parrokit-recommender:ci
          sleep 3
          curl -fsS http://localhost:8000/ || (docker logs parrokit-ci && exit 1)
          docker rm -f parrokit-ci